export const MIME_TYPE_MAP: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpeg",
  "image/gif": "gif",
  "image/webp": "webp",
  "image/svg+xml": "svg",
  "image/bmp": "bmp",
  "image/x-icon": "ico",
  "image/tiff": "tiff",
  "image/avif": "avif",
  "image/heic": "heic",
  "image/heif": "heif",
  "text/plain": "txt",
  "text/csv": "csv",
  "text/html": "html",
  "text/css": "css",
  "text/javascript": "js",
  "text/xml": "xml",
  "application/pdf": "pdf",
  "application/msword": "doc",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
    "docx",
  "application/vnd.ms-excel": "xls",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
  "application/vnd.ms-powerpoint": "ppt",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation":
    "pptx",
  "application/json": "json",
  "application/xml": "xml",
  "application/ld+json": "jsonld",
  "application/rtf": "rtf",
  "application/wasm": "wasm",
  "audio/mpeg": "mp3",
  "audio/wav": "wav",
  "audio/ogg": "ogg",
  "audio/webm": "weba",
  "audio/aac": "aac",
  "audio/midi": "midi",
  "audio/x-midi": "midi",
  "audio/flac": "flac",
  "video/mp4": "mp4",
  "video/webm": "webm",
  "video/ogg": "ogv",
  "video/x-msvideo": "avi",
  "video/mpeg": "mpeg",
  "video/quicktime": "mov",
  "application/zip": "zip",
  "application/x-rar-compressed": "rar",
  "application/x-7z-compressed": "7z",
  "application/gzip": "gz",
  "application/x-tar": "tar",
  "application/java-archive": "jar",
  "application/vnd.rar": "rar",
  "font/woff": "woff",
  "font/woff2": "woff2",
  "font/ttf": "ttf",
  "font/otf": "otf",
  "application/epub+zip": "epub",
  "application/vnd.amazon.ebook": "azw",
};

export const ALLOW_MIME_TYPES = ["png", "jpeg", "jpg", "webp", "avif", "svg"];

export const ALLOW_CONVERT_MIME_TYPES: Record<string, string[]> = {
  png: ["jpeg", "jpg", "webp", "avif", "svg", "pdf"],
  jpeg: ["png", "webp", "avif", "pdf", "svg"],
  jpg: ["png", "webp", "avif", "svg", "pdf"],
  webp: ["png", "jpeg", "jpg", "avif", "svg", "pdf"],
  avif: ["png", "jpeg", "jpg", "webp", "svg", "pdf"],
  svg: ["png", "jpeg", "jpg", "webp", "avif", "pdf"],
};
